name: Node.js CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2-beta
      with:
        node-version: '15'
        check-latest: true
    - run: yarn
    - run: REACT_APP_VERSION=${{ github.event.release.tag_name }} yarn run build
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: leishi1313/aurora-admin-frontend-test:latest
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
